#ifndef SPONSORSHIP_CONFIG_H
#define SPONSORSHIP_CONFIG_H

#include <QtCore/qglobal.h>

#define SPONSORSHIP_VERSION_MAJOR 1
#define SPONSORSHIP_VERSION_MINOR 0
#define SPONSORSHIP_VERSION_PATCH 0
#define SPONSORSHIP_VERSION       SPONSORSHIP_VERSION_CHECK(SPONSORSHIP_VERSION_MAJOR, SPONSORSHIP_VERSION_MINOR, SPONSORSHIP_VERSION_PATCH)

#define SPONSORSHIP_VERSION_STR   "1.0.0"
#define SPONSORSHIP_VERSION_CHECK(major, minor, patch) QT_VERSION_CHECK(major, minor, patch)

#ifdef QT_DEBUG
#   define SPONSORSHIP_DEBUG
#   define SPONSORSHIP_INFO
#   define SPONSORSHIP_WARNING
#   define SPONSORSHIP_CRITICAL
#   define SPONSORSHIP_FATAL
#endif

#endif // SPONSORSHIP_CONFIG_H
